### ISSUE TITLE
如何解决数据miss的问题呢？

### ISSUE THREAD

**Issue by haifeiWu** [flower-corp/lotusdb#20]
对于大量不存在的key的请求是如何处理的呢？大概看了下代码，如果key不存在的话是需要遍历内存表以及硬盘的b+ tree，或者从log中获取数据。没看到用bloomfilter来防止这样的请求呢？

**Comment by roseduan** [comment]
The query process is as you described, and I think DB shouldn`t be responsible for the problem.
