### ISSUE TITLE
Is LotusDB better than RoseDB?

### ISSUE THREAD

**Issue by lonnietc** [flower-corp/lotusdb#21]
Hello,

I am trying to determine which is the latest DB that I should be trying to use for an embedded application in development:

RoseDB
or
LotusDB

The miniDB seems to be stripped down version of RoseDB.

Can you please let me know which is best to use?

**Comment by roseduan** [comment]
It depends on your usage scenario, if you want various data structures (list, hash, set, zset), rosedb is better; on the contrary, if your data are only k/v pairs, lotusdb is a better choice (take less memory and store more data).

But lotusdb has no stable release version now, it may take a while.

**Comment by lonnietc** [comment]
Thanks for getting back to me on this.

I would like to test out RoseDB but kept running into the compile error that I reported as an issue in that repo.

**Comment by lonnietc** [comment]
Also same questions that I have for the RoseDB are for lotusDB in that:

1. Where are persistent database files kept.
2. What are the Server and Client flags and parameters and arguments.
3. What are the commands for LotusDB and example documentation for commands

These will be very helpful if you could please provide them to me.
