### ISSUE TITLE
example can not run

### ISSUE THREAD

**Issue by feeops** [flower-corp/lotusdb#25]
https://github.com/flower-corp/lotusdb/blob/main/examples/basic/basic_operation.go

../../../go/pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:114:12: assignment mismatch: 2 variables but bucket.Put returns 1 value
../../../go/pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:147:19: assignment mismatch: 2 variables but bucket.Put returns 1 value
../../../go/pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:185:19: assignment mismatch: 2 variables but bucket.Delete returns 1 value
../../../go/pkg/mod/github.com/flower-corp/lotusdb@v1.0.0/index/bptree.go:205:10: assignment mismatch: 2 variables but tx.Bucket(b.opts.BucketName).Delete returns 1 value

**Comment by roseduan** [comment]
sorry, we fork the bbolt repo and changed, try `go get github.com/flower-corp/bbolt@master`.

**Comment by prr123** [comment]
that creates a new issue
go get github.com/flower-corp/bbolt@master
go: downloading github.com/flower-corp/bbolt v1.3.7-0.20220315040627-32fed02add8f
go get: github.com/flower-corp/bbolt@v1.3.7-0.20220315040627-32fed02add8f: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/flower-corp/bbolt
