### ISSUE TITLE
Adding Dockerfile

### ISSUE THREAD

**Issue by adriang-90** [flower-corp/lotusdb#26]
Hello, 
I am wondering if there is a need for a Docker image/container in this repo?

**Comment by roseduan** [comment]
Yes, it is necessary but I don`t know how to write it yet, feel free to give me a PR!

**Comment by adriang-90** [comment]
Okay I will give it a try. Fingers crossed 🤞

**Comment by adriang-90** [comment]
> Yes, it is necessary but I don`t know how to write it yet, feel free to give me a PR!

Could you provide a more user-friendly *how to use*?

**Comment by roseduan** [comment]
> > Yes, it is necessary but I don`t know how to write it yet, feel free to give me a PR!
> 
> Could you provide a more user-friendly _how to use_?

wiki: https://github.com/flower-corp/lotusdb/wiki/Basic-Operations
LotusDB only supports embedded usage now.
