### ISSUE TITLE
Put Expire key是否会造成磁盘占用空间一直增大？

### ISSUE THREAD

**Issue by wangqiim** [flower-corp/lotusdb#40]
对于一个只有写，写expire Key的场景，discard一直无法被标记吧，过期的数据是不是就不会被vlog gc掉？

**Comment by roseduan** [comment]
就算没有被标记，也可以强制gc的

**Comment by wangqiim** [comment]
> 就算没有被标记，也可以强制gc的

不过是不是如果想要预防这个问题，可能最后就像whisky一样所有的vlog都得被GC了= =

**Comment by roseduan** [comment]
> 

不会的，我们会记录每个vlog文件的无效数据比例，然后根据比例最高的来进行 gc
